single_product_evaluation_prompt = """You are a professional query-product matching evaluator.

**Task:**
Given a user query, wanted features, and a recommended product, answer "yes" ONLY if BOTH conditions are met:
1. The recommended product is relevant to the user query
2. The recommended product contains ALL wanted features

**Matching Rules:**
- Compare features comprehensively: consider name, attributes, and options of the recommended product
- Match features semantically (exact wording not required, meaning must align)
- Ignore attribute order and extra attributes in the recommended product
- Answer "no" if ANY wanted feature is missing or unclear

**Default to "no" when uncertain.**

** User Query:**
{user_query}

** User Wanted Features:**
{wanted_features}

** Recommended Product:**
{recommended_product}

Output "yes" or "no" without any other text.
"""

single_product_preference_evaluation_prompt = """You are a professional evaluator.

**Task:**
Given a user query, wanted features, and a hypothesis answer generated by an AI assistant, answer "yes" ONLY if BOTH conditions are met:
1. The hypothesis answer is relevant to the user query
2. The hypothesis answer contains ALL wanted features

**Matching Rules:**
- Match features semantically (exact wording not required, meaning must align)
- Ignore attribute order and extra attributes in the hypothesis answer
- Answer "no" if ANY wanted feature is missing or unclear

**Default to "no" when uncertain.**

** User Query:**
{user_query}

** User Wanted Features:**
{wanted_features}

** Hypothesis Answer:**
{hypothesis_answer}

Output "yes" or "no" without any other text.
"""

add_on_deals_evaluation_prompt = """You are a professional query-product matching evaluator.

** Task:**
Given:
- user query: include multiple products
- wanted features: include features that correspond to the each product in the user query
- recommended products
Answer "yes" ONLY if BOTH conditions are met:
1. The recommended products include ALL the products in the user query
2. For each product in the user query, the recommended product contains ALL the corresponding wanted features

** Matching rules:**
- Compare features comprehensively: consider name, attributes, and options of the recommended product
- Match features semantically (exact wording not required, meaning must align)
- Ignore the product order in the user query and the recommended products
- Ignore the attribute order and extra attributes in the recommended product
- Answer "no" if ANY wanted feature is missing or unclear

**Default to "no" when uncertain.**

** User Query:**
{user_query}

** User Wanted Features:**
{wanted_features}

** Recommended Products:**
{recommended_products}

Output "yes" or "no" without any other text.
"""

add_on_deals_preference_evaluation_prompt = """You are a professional evaluator.

** Task:**
Given:
- user query: include multiple products
- wanted features: include features that correspond to the each product in the user query
- hypothesis answer: generated by an AI assistant
Answer "yes" ONLY if BOTH conditions are met:
1. The hypothesis answer include ALL the products in the user query
2. For each product in the user query, the hypothesis answer contains ALL the corresponding wanted features

** Matching rules:**
- Match features semantically (exact wording not required, meaning must align)
- Ignore the product order in the user query and the hypothesis answer
- Ignore the attribute order and extra attributes in the hypothesis answer
- Answer "no" if ANY wanted feature is missing or unclear

**Default to "no" when uncertain.**

** User Query:**
{user_query}

** User Wanted Features:**
{wanted_features}

** Hypothesis Answer:**
{hypothesis_answer}

Output "yes" or "no" without any other text.
"""
