missing_wrong_user_prompt = """# Task
Compare a hypothesis answer (generated by an AI assistant) against a reference products, and output one or more labels indicating issues.

# Inputs
- reference: one or more products. Each product includes a name and a set of required features.
- hypothesis: the assistant's answer to be evaluated.

# Definitions
- missing: The hypothesis fails to fully cover the reference.
  - Missing any entire product, or
  - Missing any required feature of any product, or
  - Only giving generic statements that do not confirm required features.
- wrong: The hypothesis introduces information not present in the reference.
  - Adds external products not in the reference, or
  - Claims features that are not listed in the reference, or
  - States information that contradicts the reference.
- all matched: The hypothesis exactly matches the reference.
  - Every product and its required features are present.
  - Every required feature is correctly matched to the reference.

# Rules
- Treat matching semantically: synonyms and paraphrases count if they clearly refer to the same product/feature.
- Every product and its required features must be present.
- Ignore details not specified in the reference (e.g., price, seller, shipping, warranty) unless explicitly included as required features.
- If both missing and wrong apply, output both labels.
- Do not include explanations, reasoning, or any extra text.

# Reference
{reference}

# Hypothesis
{hypothesis}

# Output
Return exactly one of: "missing", "wrong", or "all matched".
"""

feature_names_user_prompt = """# Task
Compare a hypothesis answer (generated by an AI assistant) against a reference products, and output the miss or wrong feature names.

# Inputs
- reference: one or more products. Each product includes a name and a set of required features.
- hypothesis: the assistant's answer to be evaluated.

# Definitions
- missing: The hypothesis fails to fully cover the reference.
  - Missing any entire product, or
  - Missing any required feature of any product, or
  - Only giving generic statements that do not confirm required features.
- wrong: The hypothesis introduces information not present in the reference.
  - Adds external products not in the reference, or
  - Claims features that are not listed in the reference, or
  - States information that contradicts the reference.

# Rules
- Treat matching semantically: synonyms and paraphrases count if they clearly refer to the same product/feature.
- Every product and its required features must be present.
- Ignore details not specified in the reference (e.g., price, seller, shipping, warranty) unless explicitly included as required features.
- If both missing and wrong apply, output both labels.
- Do not include explanations, reasoning, or any extra text.
- Only output the feature names, do not include the feature values.

# Reference
{reference}

# Hypothesis
{hypothesis}

# Output
Output a valid JSON object with "missing" and "wrong" fields.
- "missing": a valid JSON array of strings, each string is a missing feature name.
- "wrong": a valid JSON array of strings, each string is a wrong feature name.
- If the hypothesis exactly matches the reference, the "missing" and "wrong" fields should be empty arrays.
Example format:
```json
{{
    "missing": ["feature_name1", "feature_name2", ...],
    "wrong": ["feature_name3", "feature_name4", ...]
}}
```
"""